name: ci-test

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    name: Tests
    runs-on: ubuntu-latest

    services:
        postgres:
            image: postgres:16
            env:
                POSTGRES_USER: root
                POSTGRES_PASSWORD: secret
                POSTGRES_DB: simple_bank
            ports:
            - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
        id: go

      - name: set-up go-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz
          mv migrate /usr/local/bin/migrate
          which migrate

      - name: make migrate up
        run: make migrateup

      - name: Test
        run: make test
